### Login
POST http://localhost:8085/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin12345."
}

### Get Roles
GET http://localhost:8085/role
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Get Roles By ID
GET http://localhost:8085/role/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Get Users By ID
GET http://localhost:8085/user/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Get Users
GET http://localhost:8085/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Get Users
GET http://localhost:8085/user?page=0&size=5
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Delete User
DELETE http://localhost:8085/user/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Create User
POST http://localhost:8085/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA
Content-Type: application/json

{
  "username": "maintainer",
  "password": "admin1234.",
  "email": "newemail@gmail.com",
  "firstname": "Jesus",
  "lastname": "Viloria",
  "status": "INACTIVE",
  "roles": [{
    "id": 2,
    "role": "MAINTAINER",
    "status": "ACTIVE"
  }]
}

### Get Company By ID
GET http://localhost:8085/company/1
Content-Type: application/json

### Get Team List
GET http://localhost:8085/team
Content-Type: application/json

### Get DB tables sizes
GET http://localhost:8085/tables/info
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA

### Get Active Post
GET http://localhost:8085/post?page=0&size=5&sort=DESC
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6IkFETUlOIiwiZmlyc3RuYW1lIjoiSXNtYWVsIiwiaWQiOjEsImxhc3RuYW1lIjoiUGVuYSIsInVzZXJuYW1lIjoiYWRtaW4iLCJzdGF0dXMiOiJBIn0.8X5E0yElN4Nvf72EdCEa3_cAZkDKisbd__9XJ-5xq_szPva0vIeoCFDEpnsOZ19vN8tqrvgYj4KnjbUZhHZBSA
Content-Type: application/json

### Get Post By ID
GET http://localhost:8085/post/13
Content-Type: application/json

### Get Services
GET https://remodelingllc-api.herokuapp.com/services
Content-Type: application/json

### Get Service By ID
GET http://localhost:8085/services/2
Content-Type: application/json

### Get Service Thumbnail By ID
GET http://localhost:8085/services/thumbnail/2
Content-Type: application/json

### Get evidence by post ID paginated
GET http://localhost:8085/postEvidence?postId=13&page=0&size=3
Content-Type: application/json

### Get active posts paginated
GET http://localhost:8085/post?page=0&size=3
Content-Type: application/json

### Get active services paginated
GET http://localhost:8085/services?page=0&size=3
Content-Type: application/json

### Contact Email
POST http://localhost:8085/contact/email
Content-Type: application/json

{
  "subject": "My First Contact Email",
  "from": "ismaeljpv14@gmail.com",
  "message": "I wanna know the pricing for an in house remodeling",
  "phoneNumber": "+1221341221"
}

### Password recovery
GET http://localhost:8085/user/password/recovery/admin
Content-Type: application/json

### Password change
PUT http://localhost:8085/user/password/change
Content-Type: application/json

{
  "username": "admin",
  "token": "mhDf3W",
  "password": "admin1234."
}


